baseurl = "/"
title = "Lauren's Website"
author = "Lauren Klepac"
relativeurls = true
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = ""
disqusShortname = ""
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "Lauren's Website"

[[menu.main]]
    name = "Home"
    url = "https://ljanek.netlify.com"
    weight = 1
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/ljanek"
    weight = 2
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/imbisstube"
    weight = 4
